services:
  db:
    image: postgres:latest
    container_name: doutor-agenda-db
    restart: "no"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - doutor_agenda_db_data:/var/lib/postgresql/data

volumes:
  doutor_agenda_db_data:
    external: true
